const popularData = [
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 8,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 124,
    healthScore: 10,
    pricePerServing: 179.7,
    extendedIngredients: [
      {
        id: 1055062,
        aisle: "Meat",
        image: "chicken-breasts.png",
        consistency: "SOLID",
        name: "skinless boneless chicken breasts",
        nameClean: "boneless skinless chicken breast",
        original:
          "6 boneless skinless chicken breasts (I used 2 very large ones)",
        originalName:
          "boneless skinless chicken breasts (I used 2 very large ones)",
        amount: 6,
        unit: "large",
        meta: ["boneless", "skinless", "(I used 2 very large ones)"],
        measures: {
          us: {
            amount: 6,
            unitShort: "large",
            unitLong: "larges",
          },
          metric: {
            amount: 6,
            unitShort: "large",
            unitLong: "larges",
          },
        },
      },
      {
        id: 1001,
        aisle: "Milk, Eggs, Other Dairy",
        image: "butter-sliced.jpg",
        consistency: "SOLID",
        name: "butter",
        nameClean: "butter",
        original: "2 tablespoons butter",
        originalName: "butter",
        amount: 2,
        unit: "tablespoons",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 2,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 6016,
        aisle: "Canned and Jarred",
        image: "cream-of-chicken-soup.jpg",
        consistency: "LIQUID",
        name: "cream of chicken soup",
        nameClean: "condensed cream of chicken soup",
        original: "2 cans cream of chicken soup",
        originalName: "cream of chicken soup",
        amount: 2,
        unit: "cans",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "cans",
            unitLong: "cans",
          },
          metric: {
            amount: 2,
            unitShort: "cans",
            unitLong: "cans",
          },
        },
      },
      {
        id: 6194,
        aisle: "Canned and Jarred",
        image: "chicken-broth.png",
        consistency: "LIQUID",
        name: "chicken broth",
        nameClean: "chicken broth",
        original: "1 can chicken broth",
        originalName: "chicken broth",
        amount: 1,
        unit: "can",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "can",
            unitLong: "can",
          },
          metric: {
            amount: 1,
            unitShort: "can",
            unitLong: "can",
          },
        },
      },
      {
        id: 11282,
        aisle: "Produce",
        image: "brown-onion.png",
        consistency: "SOLID",
        name: "onion",
        nameClean: "onion",
        original: "1 onion diced",
        originalName: "onion diced",
        amount: 1,
        unit: "",
        meta: ["diced"],
        measures: {
          us: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 2029,
        aisle: "Spices and Seasonings",
        image: "dried-parsley.png",
        consistency: "SOLID",
        name: "dried parsley",
        nameClean: "dried parsley",
        original: "1 tablespoon dried parsley",
        originalName: "dried parsley",
        amount: 1,
        unit: "tablespoon",
        meta: ["dried"],
        measures: {
          us: {
            amount: 1,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
          metric: {
            amount: 1,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
        },
      },
      {
        id: 18009,
        aisle: "Refrigerated",
        image: "buttermilk-biscuits.jpg",
        consistency: "SOLID",
        name: "biscuits",
        nameClean: "buttermilk biscuits",
        original: "4 grands flaky refrigerator biscuits",
        originalName: "grands flaky refrigerator biscuits",
        amount: 4,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 4,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 4,
            unitShort: "",
            unitLong: "",
          },
        },
      },
    ],
    id: 640886,
    title: "Crockpot Chicken and Dumplings",
    readyInMinutes: 45,
    servings: 6,
    sourceUrl:
      "https://www.foodista.com/recipe/DJ5GP3VY/crock-pot-chicken-and-dumplings-recipe",
    openLicense: -1,
    image: "https://spoonacular.com/recipeImages/640886-556x370.jpg",
    imageType: "jpg",
    summary:
      'The recipe Crockpot Chicken and Dumplings can be made <b>in approximately approximately 45 minutes</b>. For <b>$1.8 per serving</b>, you get a main course that serves 6. One serving contains <b>330 calories</b>, <b>28g of protein</b>, and <b>16g of fat</b>. A mixture of parsley, chicken broth, onion, and a handful of other ingredients are all it takes to make this recipe so delicious. 124 people have tried and liked this recipe. It is brought to you by Foodista. All things considered, we decided this recipe <b>deserves a spoonacular score of 63%</b>. This score is solid. Similar recipes are <a href="https://spoonacular.com/recipes/crockpot-chicken-and-dumplings-891762">Crockpot chicken and dumplings</a>, <a href="https://spoonacular.com/recipes/crockpot-chicken-and-dumplings-525729">Crockpot Chicken and Dumplings</a>, and <a href="https://spoonacular.com/recipes/crockpot-chicken-dumplings-520773">Crockpot Chicken & Dumplings</a>.',
    cuisines: [],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: [],
    occasions: [],
    instructions:
      "Place chicken in the crock pot. Add butter, cream of chicken soup, chicken broth, diced onion, and parsley.\nCook on high for 4-6 hours or low for 8-10.\n30 minutes before chicken is finished cooking, cut biscuits into 9 pieces and add to crock pot. Gently stir to coat biscuits. Continue to cook for 30 minutes, then serve!",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Place chicken in the crock pot.",
            ingredients: [
              {
                id: 5006,
                name: "whole chicken",
                localizedName: "whole chicken",
                image: "whole-chicken.jpg",
              },
            ],
            equipment: [
              {
                id: 404718,
                name: "slow cooker",
                localizedName: "slow cooker",
                image: "slow-cooker.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Add butter, cream of chicken soup, chicken broth, diced onion, and parsley.",
            ingredients: [
              {
                id: 6016,
                name: "cream of chicken soup",
                localizedName: "cream of chicken soup",
                image: "cream-of-chicken-soup.jpg",
              },
              {
                id: 6194,
                name: "chicken broth",
                localizedName: "chicken broth",
                image: "chicken-broth.png",
              },
              {
                id: 11297,
                name: "parsley",
                localizedName: "parsley",
                image: "parsley.jpg",
              },
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "Cook on high for 4-6 hours or low for 8-1",
            ingredients: [],
            equipment: [],
            length: {
              number: 360,
              unit: "minutes",
            },
          },
          {
            number: 4,
            step: "30 minutes before chicken is finished cooking, cut biscuits into 9 pieces and add to crock pot. Gently stir to coat biscuits. Continue to cook for 30 minutes, then serve!",
            ingredients: [
              {
                id: 18009,
                name: "biscuits",
                localizedName: "biscuits",
                image: "buttermilk-biscuits.jpg",
              },
              {
                id: 5006,
                name: "whole chicken",
                localizedName: "whole chicken",
                image: "whole-chicken.jpg",
              },
            ],
            equipment: [
              {
                id: 404718,
                name: "slow cooker",
                localizedName: "slow cooker",
                image: "slow-cooker.jpg",
              },
            ],
            length: {
              number: 60,
              unit: "minutes",
            },
          },
        ],
      },
    ],
    sourceName: null,
    creditsText: null,
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/crockpot-chicken-and-dumplings-640886",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 19,
    gaps: "no",
    preparationMinutes: 15,
    cookingMinutes: 25,
    aggregateLikes: 11,
    healthScore: 63,
    creditsText: "Jen West",
    sourceName: "Pink When",
    pricePerServing: 481.76,
    extendedIngredients: [
      {
        id: 10211821,
        aisle: "Produce",
        image: "bell-pepper-orange.png",
        consistency: "SOLID",
        name: "bell pepper",
        nameClean: "bell pepper",
        original: "1/2 cup diced bell pepper",
        originalName: "diced bell pepper",
        amount: 0.5,
        unit: "cup",
        meta: ["diced"],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 118.294,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "SOLID",
        name: "garlic",
        nameClean: "garlic",
        original: "1 clove garlic diced",
        originalName: "garlic diced",
        amount: 1,
        unit: "clove",
        meta: ["diced"],
        measures: {
          us: {
            amount: 1,
            unitShort: "clove",
            unitLong: "clove",
          },
          metric: {
            amount: 1,
            unitShort: "clove",
            unitLong: "clove",
          },
        },
      },
      {
        id: 5662,
        aisle: "Meat",
        image: "meat-ground.jpg",
        consistency: "SOLID",
        name: "lean ground turkey",
        nameClean: "ground turkey",
        original: "1 1/2 pounds lean ground turkey",
        originalName: "lean ground turkey",
        amount: 1.5,
        unit: "pounds",
        meta: ["lean"],
        measures: {
          us: {
            amount: 1.5,
            unitShort: "lb",
            unitLong: "pounds",
          },
          metric: {
            amount: 680.389,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 4053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "LIQUID",
        name: "olive oil",
        nameClean: "olive oil",
        original: "olive oil",
        originalName: "olive oil",
        amount: 4,
        unit: "servings",
        meta: [],
        measures: {
          us: {
            amount: 4,
            unitShort: "servings",
            unitLong: "servings",
          },
          metric: {
            amount: 4,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
      {
        id: 11282,
        aisle: "Produce",
        image: "brown-onion.png",
        consistency: "SOLID",
        name: "onion",
        nameClean: "onion",
        original: "1/2 cup diced onion",
        originalName: "diced onion",
        amount: 0.5,
        unit: "cup",
        meta: ["diced"],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 118.294,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 1102047,
        aisle: "Spices and Seasonings",
        image: "salt-and-pepper.jpg",
        consistency: "SOLID",
        name: "salt and pepper",
        nameClean: "salt and pepper",
        original: "salt and pepper to taste",
        originalName: "salt and pepper to taste",
        amount: 4,
        unit: "servings",
        meta: ["to taste"],
        measures: {
          us: {
            amount: 4,
            unitShort: "servings",
            unitLong: "servings",
          },
          metric: {
            amount: 4,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
      {
        id: 11507,
        aisle: "Produce",
        image: "sweet-potato.png",
        consistency: "SOLID",
        name: "sweet potatoes",
        nameClean: "sweet potato",
        original: "4 large sweet potatoes",
        originalName: "sweet potatoes",
        amount: 4,
        unit: "large",
        meta: [],
        measures: {
          us: {
            amount: 4,
            unitShort: "large",
            unitLong: "larges",
          },
          metric: {
            amount: 4,
            unitShort: "large",
            unitLong: "larges",
          },
        },
      },
      {
        id: 11887,
        aisle: "Pasta and Rice",
        image: "tomato-paste.jpg",
        consistency: "SOLID",
        name: "tomato paste",
        nameClean: "tomato paste",
        original: "6 ounces tomato paste",
        originalName: "tomato paste",
        amount: 6,
        unit: "ounces",
        meta: [],
        measures: {
          us: {
            amount: 6,
            unitShort: "oz",
            unitLong: "ounces",
          },
          metric: {
            amount: 170.097,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 11549,
        aisle: "Pasta and Rice",
        image: "tomato-sauce-or-pasta-sauce.jpg",
        consistency: "SOLID",
        name: "tomato sauce",
        nameClean: "canned tomato sauce",
        original: "14 ounces tomato sauce",
        originalName: "tomato sauce",
        amount: 14,
        unit: "ounces",
        meta: [],
        measures: {
          us: {
            amount: 14,
            unitShort: "oz",
            unitLong: "ounces",
          },
          metric: {
            amount: 396.893,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 14412,
        aisle: "Beverages",
        image: "water.png",
        consistency: "LIQUID",
        name: "water",
        nameClean: "water",
        original: "1 cup water",
        originalName: "water",
        amount: 1,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "cup",
            unitLong: "cup",
          },
          metric: {
            amount: 236.588,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
    ],
    id: 1046982,
    title: "How to Make the Perfect Sweet Potato Sloppy Joes",
    readyInMinutes: 40,
    servings: 4,
    sourceUrl:
      "https://www.pinkwhen.com/how-to-make-the-perfect-sweet-potato-sloppy-joes/",
    openLicense: -1,
    image: "https://spoonacular.com/recipeImages/1046982-556x370.jpg",
    imageType: "jpg",
    summary:
      'How to Make the Perfect Sweet Potato Sloppy Joes might be just the <b>American</b> recipe you are searching for. One portion of this dish contains roughly <b>46g of protein</b>, <b>7g of fat</b>, and a total of <b>407 calories</b>. For <b>$3.99 per serving</b>, you get a main course that serves 4. 10 people have tried and liked this recipe. Head to the store and pick up salt and pepper, water, ground turkey, and a few other things to make it today. It is a good option if you\'re following a <b>gluten free, dairy free, paleolithic, and primal</b> diet. From preparation to the plate, this recipe takes around <b>40 minutes</b>. It is brought to you by Pink When. Overall, this recipe earns a <b>solid spoonacular score of 50%</b>. Similar recipes are <a href="https://spoonacular.com/recipes/just-perfect-sloppy-joes-82826">Just Perfect Sloppy Joes</a>, <a href="https://spoonacular.com/recipes/how-to-make-classic-sloppy-joes-471307">How to Make Classic Sloppy Joes</a>, and <a href="https://spoonacular.com/recipes/make-ahead-sloppy-joes-428874">Make-Ahead Sloppy Joes</a>.',
    cuisines: ["American"],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free", "paleolithic", "primal", "whole 30"],
    occasions: [],
    instructions:
      "Instructions\n\n\n\nPreheat the oven to 425 degrees. Pierce the sweet potatoes all over the skin with a fork. Rub the outside of the potatoes with olive oil and cover with foil. Bake in the oven for 1 hour until fully cooked.\n\n\nBrown the ground turkey in a skillet on medium heat. Once it's finished cooking, add the onion, bell pepper, and garlic. Mix well. Cook until the mixture is fully cooked and starts to crumble.\n\n\nStir in the garlic, water, tomato paste, and tomato sauce. Stir until mixed well. Turn heat down to low and simmer for 20 minutes, stirring occasionally.\n\n\nRemove the sweet potatoes from the foil and slice down the middle. Mash up the insides with a fork and pour the sloppy joe mix over sweet potatoes. Serve and enjoy!",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Preheat the oven to 425 degrees. Pierce the sweet potatoes all over the skin with a fork. Rub the outside of the potatoes with olive oil and cover with foil.",
            ingredients: [
              {
                id: 11507,
                name: "sweet potato",
                localizedName: "sweet potato",
                image: "sweet-potato.png",
              },
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
              {
                id: 11352,
                name: "potato",
                localizedName: "potato",
                image: "potatoes-yukon-gold.png",
              },
              {
                id: 1012034,
                name: "dry seasoning rub",
                localizedName: "dry seasoning rub",
                image: "seasoning.png",
              },
            ],
            equipment: [
              {
                id: 404765,
                name: "aluminum foil",
                localizedName: "aluminum foil",
                image: "aluminum-foil.png",
              },
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Bake in the oven for 1 hour until fully cooked.",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
            length: {
              number: 60,
              unit: "minutes",
            },
          },
          {
            number: 3,
            step: "Brown the ground turkey in a skillet on medium heat. Once it's finished cooking, add the onion, bell pepper, and garlic.",
            ingredients: [
              {
                id: 5662,
                name: "ground turkey",
                localizedName: "ground turkey",
                image: "meat-ground.jpg",
              },
              {
                id: 10211821,
                name: "bell pepper",
                localizedName: "bell pepper",
                image: "bell-pepper-orange.png",
              },
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
          },
          {
            number: 4,
            step: "Mix well. Cook until the mixture is fully cooked and starts to crumble.",
            ingredients: [],
            equipment: [],
          },
          {
            number: 5,
            step: "Stir in the garlic, water, tomato paste, and tomato sauce. Stir until mixed well. Turn heat down to low and simmer for 20 minutes, stirring occasionally.",
            ingredients: [
              {
                id: 11887,
                name: "tomato paste",
                localizedName: "tomato paste",
                image: "tomato-paste.jpg",
              },
              {
                id: 11549,
                name: "tomato sauce",
                localizedName: "tomato sauce",
                image: "tomato-sauce-or-pasta-sauce.jpg",
              },
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
            ],
            equipment: [],
            length: {
              number: 20,
              unit: "minutes",
            },
          },
          {
            number: 6,
            step: "Remove the sweet potatoes from the foil and slice down the middle. Mash up the insides with a fork and pour the sloppy joe mix over sweet potatoes.",
            ingredients: [
              {
                id: 11507,
                name: "sweet potato",
                localizedName: "sweet potato",
                image: "sweet-potato.png",
              },
            ],
            equipment: [
              {
                id: 404765,
                name: "aluminum foil",
                localizedName: "aluminum foil",
                image: "aluminum-foil.png",
              },
            ],
          },
          {
            number: 7,
            step: "Serve and enjoy!",
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/how-to-make-the-perfect-sweet-potato-sloppy-joes-1046982",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 21,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 85,
    healthScore: 92,
    creditsText: "Afrolems",
    license: "CC BY 4.0",
    sourceName: "Afrolems",
    pricePerServing: 566.5,
    extendedIngredients: [
      {
        id: 1001,
        aisle: "Milk, Eggs, Other Dairy",
        image: "butter-sliced.jpg",
        consistency: "SOLID",
        name: "butter",
        nameClean: "butter",
        original: "1 teaspoon of Butter",
        originalName: "Butter",
        amount: 1,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 5062,
        aisle: "Meat",
        image: "chicken-breasts.png",
        consistency: "SOLID",
        name: "chicken breasts",
        nameClean: "chicken breast",
        original: "2 Chicken Breasts",
        originalName: "Chicken Breasts",
        amount: 2,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 2009,
        aisle: "Spices and Seasonings",
        image: "chili-powder.jpg",
        consistency: "SOLID",
        name: "chilli powder",
        nameClean: "chili powder",
        original: "1/2 teaspoon of chilli powder",
        originalName: "chilli powder",
        amount: 0.5,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 93605,
        aisle: "Ethnic Foods",
        image: "chili-paste.png",
        consistency: "SOLID",
        name: "curry paste",
        nameClean: "red curry paste",
        original: "1 teaspoon of curry",
        originalName: "curry",
        amount: 1,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "SOLID",
        name: "garlic cloves",
        nameClean: "garlic",
        original: "2 garlic cloves",
        originalName: "garlic cloves",
        amount: 2,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 2021,
        aisle: "Spices and Seasonings",
        image: "ginger.png",
        consistency: "SOLID",
        name: "ginger powder",
        nameClean: "ginger powder",
        original:
          "1/2 teaspoon of ginger powder (small chunk of ginger equivalent)",
        originalName: "ginger powder (small chunk of ginger equivalent)",
        amount: 0.5,
        unit: "teaspoon",
        meta: ["chunk", "(small of ginger equivalent)"],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 10014412,
        aisle: "Frozen",
        image: "ice-cubes.png",
        consistency: "SOLID",
        name: "ice cubes",
        nameClean: "ice",
        original: "2 seasoning cubes",
        originalName: "seasoning cubes",
        amount: 2,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 11282,
        aisle: "Produce",
        image: "brown-onion.png",
        consistency: "SOLID",
        name: "onions",
        nameClean: "onion",
        original: "A handful of sliced onions",
        originalName: "A of sliced onions",
        amount: 1,
        unit: "handful",
        meta: ["sliced"],
        measures: {
          us: {
            amount: 1,
            unitShort: "handful",
            unitLong: "handful",
          },
          metric: {
            amount: 1,
            unitShort: "handful",
            unitLong: "handful",
          },
        },
      },
      {
        id: 11352,
        aisle: "Produce",
        image: "potatoes-yukon-gold.png",
        consistency: "SOLID",
        name: "potatoes",
        nameClean: "potato",
        original: "2 large potatoes",
        originalName: "potatoes",
        amount: 2,
        unit: "large",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "large",
            unitLong: "larges",
          },
          metric: {
            amount: 2,
            unitShort: "large",
            unitLong: "larges",
          },
        },
      },
      {
        id: 14412,
        aisle: "Beverages",
        image: "water.png",
        consistency: "LIQUID",
        name: "water",
        nameClean: "water",
        original: "1/3 cup water",
        originalName: "water",
        amount: 0.33333334,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.333,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 78.863,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 1116,
        aisle: "Milk, Eggs, Other Dairy",
        image: "plain-yogurt.jpg",
        consistency: "SOLID",
        name: "yoghurt",
        nameClean: "yogurt",
        original: "2 tablespoons of plain yoghurt",
        originalName: "plain yoghurt",
        amount: 2,
        unit: "tablespoons",
        meta: ["plain"],
        measures: {
          us: {
            amount: 2,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 2,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
    ],
    id: 716356,
    title: "Yoghurt Chicken and Garlic Potatoes",
    readyInMinutes: 45,
    servings: 1,
    sourceUrl:
      "http://www.afrolems.com/2014/03/22/yoghurt-chicken-and-garlic-potatoes/",
    openLicense: -1,
    image: "https://spoonacular.com/recipeImages/716356-556x370.jpg",
    imageType: "jpg",
    summary:
      'Yoghurt Chicken and Garlic Potatoes might be just the main course you are searching for. For <b>$3.25 per serving</b>, this recipe <b>covers 47%</b> of your daily requirements of vitamins and minerals. This recipe makes 1 servings with <b>586 calories</b>, <b>61g of protein</b>, and <b>12g of fat</b> each. A few people made this recipe, and 85 would say it hit the spot. If you have water, seasoning cubes, yoghurt, and a few other ingredients on hand, you can make it. To use up the ice cubes you could follow this main course with the <a href="https://spoonacular.com/recipes/nectarine-blackberry-and-pecan-sundaes-50465">Nectarine, Blackberry, and Pecan Sundaes</a> as a dessert. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. It is a good option if you\'re following a <b>gluten free</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 99%</b>. This score is spectacular. Try <a href="https://spoonacular.com/recipes/grilled-chicken-guacamole-taco-with-garlic-yoghurt-tahini-sauce-623194">Grilled Chicken & Guacamole Taco with Garlic-Yoghurt-Tahini Sauce</a>, <a href="https://spoonacular.com/recipes/beef-mince-and-macaroni-with-a-yoghurt-garlic-sauce-144499">Beef Mince and Macaroni with a Yoghurt-Garlic-Sauce</a>, and <a href="https://spoonacular.com/recipes/chicken-with-yoghurt-124458">Chicken with Yoghurt</a> for similar recipes.',
    cuisines: [],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free"],
    occasions: [],
    instructions:
      "Blend the yoghurt, curry, seasoning cubes, ginger powder, chilli powder and water together.Pour over chicken and leave to marinate for a few hours. (2~3 hours should be fine)Heat up the oven to 380F, sprInkle the marinated chicken with the sliced onions and place the chicken to cook for 35~40 minutes.In a pot, wash your potatoes and place in the pot to boil.Crush your garlic cloves and mix with the butter.Once the potatoes are soft, drain the water out, rub the garlic butter on the potatoes and sprinkle your basil leaves on it, I boiled my potatoes with its skin because I wanted the extra fibre content.Serve with the chicken when its ready. ",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Blend the yoghurt, curry, seasoning cubes, ginger powder, chilli powder and water together.",
            ingredients: [
              {
                id: 0,
                name: "seasoning cube",
                localizedName: "seasoning cube",
                image: "stock-cube.jpg",
              },
              {
                id: 2009,
                name: "chili powder",
                localizedName: "chili powder",
                image: "chili-powder.jpg",
              },
              {
                id: 2021,
                name: "ginger powder",
                localizedName: "ginger powder",
                image: "ginger.png",
              },
              {
                id: 1116,
                name: "yogurt",
                localizedName: "yogurt",
                image: "plain-yogurt.jpg",
              },
              {
                id: 2015,
                name: "curry powder",
                localizedName: "curry powder",
                image: "curry-powder.jpg",
              },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
            ],
            equipment: [],
          },
          {
            number: 2,
            step: "Pour over chicken and leave to marinate for a few hours. (2~3 hours should be fine)",
            ingredients: [
              {
                id: 5006,
                name: "whole chicken",
                localizedName: "whole chicken",
                image: "whole-chicken.jpg",
              },
            ],
            equipment: [],
            length: {
              number: 180,
              unit: "minutes",
            },
          },
          {
            number: 3,
            step: "Heat up the oven to 380F, spr",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
                temperature: {
                  number: 380,
                  unit: "Fahrenheit",
                },
              },
            ],
          },
          {
            number: 4,
            step: "Inkle the marinated chicken with the sliced onions and place the chicken to cook for 35~40 minutes.In a pot, wash your potatoes and place in the pot to boil.Crush your garlic cloves and mix with the butter.Once the potatoes are soft, drain the water out, rub the garlic butter on the potatoes and sprinkle your basil leaves on it, I boiled my potatoes with its skin because I wanted the extra fibre content.",
            ingredients: [
              {
                id: 2044,
                name: "fresh basil",
                localizedName: "fresh basil",
                image: "fresh-basil.jpg",
              },
              {
                id: 11352,
                name: "potato",
                localizedName: "potato",
                image: "potatoes-yukon-gold.png",
              },
              {
                id: 5006,
                name: "whole chicken",
                localizedName: "whole chicken",
                image: "whole-chicken.jpg",
              },
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
              {
                id: 1002011,
                name: "clove",
                localizedName: "clove",
                image: "cloves.jpg",
              },
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
              {
                id: 1012034,
                name: "dry seasoning rub",
                localizedName: "dry seasoning rub",
                image: "seasoning.png",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
            length: {
              number: 40,
              unit: "minutes",
            },
          },
          {
            number: 5,
            step: "Serve with the chicken when its ready. ",
            ingredients: [
              {
                id: 5006,
                name: "whole chicken",
                localizedName: "whole chicken",
                image: "whole-chicken.jpg",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/yoghurt-chicken-and-garlic-potatoes-716356",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 1,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 83,
    healthScore: 0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 34.82,
    extendedIngredients: [
      {
        id: 10123,
        aisle: "Meat",
        image: "raw-bacon.png",
        consistency: "SOLID",
        name: "bacon",
        nameClean: "applewood smoked bacon",
        original: "1 inch oz. Bacon cut in ¼ strips",
        originalName: "oz. Bacon cut in ¼ strips",
        amount: 1,
        unit: "inch",
        meta: ["cut in ¼ strips"],
        measures: {
          us: {
            amount: 1,
            unitShort: "inch",
            unitLong: "inch",
          },
          metric: {
            amount: 1,
            unitShort: "inch",
            unitLong: "inch",
          },
        },
      },
      {
        id: 6159,
        aisle: "Canned and Jarred",
        image: "tomato-soup.png",
        consistency: "LIQUID",
        name: "tomato soup",
        nameClean: "tomato soup",
        original: "1 can Your favorite All Natural Tomato soup",
        originalName: "Your favorite All Natural Tomato soup",
        amount: 1,
        unit: "can",
        meta: ["your favorite"],
        measures: {
          us: {
            amount: 1,
            unitShort: "can",
            unitLong: "can",
          },
          metric: {
            amount: 1,
            unitShort: "can",
            unitLong: "can",
          },
        },
      },
      {
        id: 6615,
        aisle: "Canned and Jarred",
        image: "chicken-broth.png",
        consistency: "LIQUID",
        name: "vegetable stock",
        nameClean: "vegetable stock",
        original: "1 cup Vegetable Stock",
        originalName: "Vegetable Stock",
        amount: 1,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "cup",
            unitLong: "cup",
          },
          metric: {
            amount: 236.588,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 6233,
        aisle: "Pasta and Rice",
        image: "tomato-sauce-or-pasta-sauce.jpg",
        consistency: "SOLID",
        name: "tomato & basil sauce",
        nameClean: "tomato and basil sauce",
        original:
          "1 6.5 oz pkg. Alouette All Natural Sundried Tomato and Basil soft spreadable cheese",
        originalName:
          "pkg. Alouette All Natural Sundried Tomato and Basil soft spreadable cheese",
        amount: 6.5,
        unit: "oz",
        meta: ["soft"],
        measures: {
          us: {
            amount: 6.5,
            unitShort: "oz",
            unitLong: "ounces",
          },
          metric: {
            amount: 184.272,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
    ],
    id: 632250,
    title: "Alouette Sundried Tomato and Basil Bisque",
    readyInMinutes: 45,
    servings: 8,
    sourceUrl:
      "https://www.foodista.com/recipe/PQVZCRLT/alouette-sundried-tomato-and-basil-bisque",
    openLicense: -1,
    image: "https://spoonacular.com/recipeImages/632250-556x370.jpg",
    imageType: "jpg",
    summary:
      'Alouette Sundried Tomato and Basil Bisque might be a good recipe to expand your soup recipe box. Watching your figure? This gluten free and dairy free recipe has <b>44 calories</b>, <b>1g of protein</b>, and <b>1g of fat</b> per serving. This recipe serves 8 and costs 35 cents per serving. 83 people were impressed by this recipe. It is brought to you by Foodista. From preparation to the plate, this recipe takes roughly <b>roughly 45 minutes</b>. Head to the store and pick up bacon, all natural tomato soup, alouette all natural sundried tomato and basil spreadable cheese, and a few other things to make it today. Taking all factors into account, this recipe <b>earns a spoonacular score of 22%</b>, which is rather bad. Try <a href="https://spoonacular.com/recipes/sundried-tomato-basil-and-goats-cheese-pasta-27264">Sundried Tomato, Basil And Goats Cheese Pasta</a>, <a href="https://spoonacular.com/recipes/sundried-tomato-and-basil-cream-cheese-spread-594907">Sundried Tomato and Basil Cream Cheese Spread</a>, and <a href="https://spoonacular.com/recipes/tomato-basil-bisque-211806">Tomato-Basil Bisque</a> for similar recipes.',
    cuisines: [],
    dishTypes: ["soup"],
    diets: ["gluten free", "dairy free"],
    occasions: [],
    instructions:
      "Saut bacon in heavy gauge sauce pot until crispy\nDrain fat from sauce pot\nAdd Tomato soup and vegetable stock and bring to a boil\nAdd Alouette Sundried Tomato and Basil soft cheese\nBring back to a boil and serve",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Saut bacon in heavy gauge sauce pot until crispy",
            ingredients: [
              {
                id: 10123,
                name: "bacon",
                localizedName: "bacon",
                image: "raw-bacon.png",
              },
              {
                id: 0,
                name: "sauce",
                localizedName: "sauce",
                image: "",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Drain fat from sauce pot",
            ingredients: [
              {
                id: 0,
                name: "sauce",
                localizedName: "sauce",
                image: "",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
          {
            number: 3,
            step: "Add Tomato soup and vegetable stock and bring to a boil",
            ingredients: [
              {
                id: 6615,
                name: "vegetable stock",
                localizedName: "vegetable stock",
                image: "chicken-broth.png",
              },
              {
                id: 6159,
                name: "tomato soup",
                localizedName: "tomato soup",
                image: "tomato-soup.png",
              },
            ],
            equipment: [],
          },
          {
            number: 4,
            step: "Add Alouette Sundried Tomato and Basil soft cheese",
            ingredients: [
              {
                id: 1001017,
                name: "soft cheese",
                localizedName: "soft cheese",
                image: "cream-cheese.jpg",
              },
              {
                id: 11529,
                name: "tomato",
                localizedName: "tomato",
                image: "tomato.png",
              },
              {
                id: 2044,
                name: "basil",
                localizedName: "basil",
                image: "basil.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 5,
            step: "Bring back to a boil and serve",
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/alouette-sundried-tomato-and-basil-bisque-632250",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: true,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 16,
    gaps: "no",
    preparationMinutes: 5,
    cookingMinutes: 6,
    aggregateLikes: 641,
    healthScore: 8,
    pricePerServing: 144.53,
    extendedIngredients: [
      {
        id: 1001,
        aisle: "Milk, Eggs, Other Dairy",
        image: "butter-sliced.jpg",
        consistency: "SOLID",
        name: "butter",
        nameClean: "butter",
        original: "4 tbsp butter",
        originalName: "butter",
        amount: 4,
        unit: "tbsp",
        meta: [],
        measures: {
          us: {
            amount: 4,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 4,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 18009,
        aisle: "Refrigerated",
        image: "buttermilk-biscuits.jpg",
        consistency: "SOLID",
        name: "canned biscuits",
        nameClean: "buttermilk biscuits",
        original: "1 can of biscuits ( I used Pillsbury® Grands)",
        originalName: "biscuits ( I used Pillsbury® Grands)",
        amount: 1,
        unit: "can",
        meta: ["pillsbury®", "( I used Grands)"],
        measures: {
          us: {
            amount: 1,
            unitShort: "can",
            unitLong: "can",
          },
          metric: {
            amount: 1,
            unitShort: "can",
            unitLong: "can",
          },
        },
      },
      {
        id: 6016,
        aisle: "Canned and Jarred",
        image: "cream-of-chicken-soup.jpg",
        consistency: "LIQUID",
        name: "condensed cream of chicken soup",
        nameClean: "condensed cream of chicken soup",
        original: "2 cans condensed cream of chicken soup",
        originalName: "condensed cream of chicken soup",
        amount: 2,
        unit: "cans",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "cans",
            unitLong: "cans",
          },
          metric: {
            amount: 2,
            unitShort: "cans",
            unitLong: "cans",
          },
        },
      },
      {
        id: 20081,
        aisle: "Baking",
        image: "flour.png",
        consistency: "SOLID",
        name: "flour",
        nameClean: "wheat flour",
        original: "1 Tbsp flour",
        originalName: "flour",
        amount: 1,
        unit: "Tbsp",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
          metric: {
            amount: 1,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
        },
      },
      {
        id: 11282,
        aisle: "Produce",
        image: "brown-onion.png",
        consistency: "SOLID",
        name: "onion",
        nameClean: "onion",
        original: "1 finely chopped onion",
        originalName: "finely chopped onion",
        amount: 1,
        unit: "",
        meta: ["finely chopped"],
        measures: {
          us: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 11297,
        aisle: "Produce;Spices and Seasonings",
        image: "parsley.jpg",
        consistency: "SOLID",
        name: "parsley",
        nameClean: "parsley",
        original: "1 tsp parsley",
        originalName: "parsley",
        amount: 1,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 1002030,
        aisle: "Spices and Seasonings",
        image: "pepper.jpg",
        consistency: "SOLID",
        name: "pepper",
        nameClean: "black pepper",
        original: "1 tsp pepper",
        originalName: "pepper",
        amount: 1,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 2034,
        aisle: "Spices and Seasonings",
        image: "seasoning.jpg",
        consistency: "SOLID",
        name: "poultry seasoning",
        nameClean: "poultry seasoning",
        original: "2 tsp poultry seasoning",
        originalName: "poultry seasoning",
        amount: 2,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 2,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 1055062,
        aisle: "Meat",
        image: "chicken-breasts.png",
        consistency: "SOLID",
        name: "skinless boneless chicken breasts",
        nameClean: "boneless skinless chicken breast",
        original: "3 boneless skinless chicken breasts",
        originalName: "boneless skinless chicken breasts",
        amount: 3,
        unit: "",
        meta: ["boneless", "skinless"],
        measures: {
          us: {
            amount: 3,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 3,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 14412,
        aisle: "Beverages",
        image: "water.png",
        consistency: "LIQUID",
        name: "water",
        nameClean: "water",
        original: "2 cups water",
        originalName: "water",
        amount: 2,
        unit: "cups",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 473.176,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
    ],
    id: 715383,
    title: "Slow Cooker Chicken and Dumplings",
    readyInMinutes: 11,
    servings: 6,
    sourceUrl: "http://www.pinkwhen.com/slow-cooker-chicken-and-dumplings/",
    openLicense: -1,
    image: "https://spoonacular.com/recipeImages/715383-556x370.jpg",
    imageType: "jpg",
    summary:
      'Slow Cooker Chicken and Dumplings might be just the main course you are searching for. For <b>$1.45 per serving</b>, this recipe <b>covers 17%</b> of your daily requirements of vitamins and minerals. This recipe makes 6 servings with <b>519 calories</b>, <b>20g of protein</b>, and <b>28g of fat</b> each. 639 people were impressed by this recipe. From preparation to the plate, this recipe takes approximately <b>11 minutes</b>. A mixture of flour, chicken breasts, parsley, and a handful of other ingredients are all it takes to make this recipe so scrumptious. All things considered, we decided this recipe <b>deserves a spoonacular score of 73%</b>. This score is solid. Try <a href="https://spoonacular.com/recipes/slow-cooker-chicken-and-dumplings-94710">Slow Cooker Chicken and Dumplings</a>, <a href="https://spoonacular.com/recipes/slow-cooker-chicken-and-dumplings-596946">Slow Cooker Chicken and Dumplings</a>, and <a href="https://spoonacular.com/recipes/slow-cooker-chicken-and-dumplings-686869">Slow Cooker Chicken and Dumplings</a> for similar recipes.',
    cuisines: [],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: [],
    occasions: [],
    instructions:
      "Place Slow Cooker on high.Add chicken breasts, butter, water, soup, flour, onion, poultry seasoning, pepper, and parsley. Stir and mix well. Cook on high for 4 hours. Take two forks and start shredding chicken in the mixture.After shredding chicken, tear small pieces of biscuit dough and place in slow cooker for remaining 2 hours. Stirring occasionally.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Place Slow Cooker on high.",
            ingredients: [],
            equipment: [
              {
                id: 404718,
                name: "slow cooker",
                localizedName: "slow cooker",
                image: "slow-cooker.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Add chicken breasts, butter, water, soup, flour, onion, poultry seasoning, pepper, and parsley. Stir and mix well. Cook on high for 4 hours. Take two forks and start shredding chicken in the mixture.After shredding chicken, tear small pieces of biscuit dough and place in slow cooker for remaining 2 hours. Stirring occasionally.",
            ingredients: [
              {
                id: 2034,
                name: "poultry seasoning",
                localizedName: "poultry seasoning",
                image: "seasoning.jpg",
              },
              {
                id: 5062,
                name: "chicken breast",
                localizedName: "chicken breast",
                image: "chicken-breasts.png",
              },
              {
                id: 18009,
                name: "biscuits",
                localizedName: "biscuits",
                image: "buttermilk-biscuits.jpg",
              },
              {
                id: 5006,
                name: "whole chicken",
                localizedName: "whole chicken",
                image: "whole-chicken.jpg",
              },
              {
                id: 11297,
                name: "parsley",
                localizedName: "parsley",
                image: "parsley.jpg",
              },
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
              {
                id: 1002030,
                name: "pepper",
                localizedName: "pepper",
                image: "pepper.jpg",
              },
              {
                id: 20081,
                name: "all purpose flour",
                localizedName: "all purpose flour",
                image: "flour.png",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
              {
                id: 0,
                name: "soup",
                localizedName: "soup",
                image: "",
              },
            ],
            equipment: [
              {
                id: 404718,
                name: "slow cooker",
                localizedName: "slow cooker",
                image: "slow-cooker.jpg",
              },
            ],
            length: {
              number: 360,
              unit: "minutes",
            },
          },
        ],
      },
    ],
    sourceName: null,
    creditsText: null,
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/slow-cooker-chicken-and-dumplings-715383",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 30,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 9,
    healthScore: 20,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 646.43,
    extendedIngredients: [
      {
        id: 23232,
        aisle: "Meat",
        image: "ribeye-raw.jpg",
        consistency: "SOLID",
        name: "beef steak",
        nameClean: "steak",
        original: "400g beef steak (minute steak from leg)",
        originalName: "beef steak (minute steak from leg)",
        amount: 400,
        unit: "g",
        meta: ["(minute steak from leg)"],
        measures: {
          us: {
            amount: 14.11,
            unitShort: "oz",
            unitLong: "ounces",
          },
          metric: {
            amount: 400,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 1001,
        aisle: "Milk, Eggs, Other Dairy",
        image: "butter-sliced.jpg",
        consistency: "SOLID",
        name: "butter",
        nameClean: "butter",
        original: "2 tablespoons Butter",
        originalName: "Butter",
        amount: 2,
        unit: "tablespoons",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 2,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 2054,
        aisle: "Canned and Jarred",
        image: "capers.jpg",
        consistency: "SOLID",
        name: "capers",
        nameClean: "capers",
        original: "2 Tbs capers",
        originalName: "capers",
        amount: 2,
        unit: "Tbs",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "Tbs",
            unitLong: "Tbs",
          },
          metric: {
            amount: 2,
            unitShort: "Tbs",
            unitLong: "Tbs",
          },
        },
      },
      {
        id: 14106,
        aisle: "Alcoholic Beverages",
        image: "white-wine.jpg",
        consistency: "LIQUID",
        name: "dry white wine",
        nameClean: "dry white wine",
        original: "¾ cup dry white wine",
        originalName: "dry white wine",
        amount: 0.75,
        unit: "cup",
        meta: ["dry white"],
        measures: {
          us: {
            amount: 0.75,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 177.441,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 20081,
        aisle: "Baking",
        image: "flour.png",
        consistency: "SOLID",
        name: "flour",
        nameClean: "wheat flour",
        original: "1 cup flour",
        originalName: "flour",
        amount: 1,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "cup",
            unitLong: "cup",
          },
          metric: {
            amount: 236.588,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "SOLID",
        name: "garlic",
        nameClean: "garlic",
        original: "2 to 3 large cloves garlic, pressed",
        originalName: "garlic, pressed",
        amount: 2,
        unit: "large cloves",
        meta: ["pressed"],
        measures: {
          us: {
            amount: 2,
            unitShort: "large cloves",
            unitLong: "large cloves",
          },
          metric: {
            amount: 2,
            unitShort: "large cloves",
            unitLong: "large cloves",
          },
        },
      },
      {
        id: 1002030,
        aisle: "Spices and Seasonings",
        image: "pepper.jpg",
        consistency: "SOLID",
        name: "ground pepper",
        nameClean: "black pepper",
        original: "¼ tsp ground black pepper",
        originalName: "ground black pepper",
        amount: 0.25,
        unit: "tsp",
        meta: ["black"],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 9152,
        aisle: "Produce",
        image: "lemon-juice.jpg",
        consistency: "LIQUID",
        name: "lemon juice",
        nameClean: "lemon juice",
        original: "1 teaspoon lemon juice",
        originalName: "lemon juice",
        amount: 1,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 1029150,
        aisle: "Produce",
        image: "lemon-wedge.png",
        consistency: "SOLID",
        name: "lemon wedges",
        nameClean: "lemon wedge",
        original: "Lemon wedges",
        originalName: "Lemon wedges",
        amount: 2,
        unit: "servings",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "servings",
            unitLong: "servings",
          },
          metric: {
            amount: 2,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
      {
        id: 4053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "LIQUID",
        name: "olive oil",
        nameClean: "olive oil",
        original: "2 Tbs olive oil",
        originalName: "olive oil",
        amount: 2,
        unit: "Tbs",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "Tbs",
            unitLong: "Tbs",
          },
          metric: {
            amount: 2,
            unitShort: "Tbs",
            unitLong: "Tbs",
          },
        },
      },
      {
        id: 11297,
        aisle: "Produce;Spices and Seasonings",
        image: "parsley.jpg",
        consistency: "SOLID",
        name: "parsley",
        nameClean: "parsley",
        original: "2 teaspoons parsley, finely chopped",
        originalName: "parsley, finely chopped",
        amount: 2,
        unit: "teaspoons",
        meta: ["finely chopped"],
        measures: {
          us: {
            amount: 2,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 2,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 2047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "SOLID",
        name: "salt",
        nameClean: "table salt",
        original: "¾ tsp salt",
        originalName: "salt",
        amount: 0.75,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 0.75,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.75,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
    ],
    id: 661531,
    title: "Steak with lemon and capers",
    readyInMinutes: 45,
    servings: 2,
    sourceUrl:
      "http://www.foodista.com/recipe/JKGPWDDP/steak-with-lemon-and-capers",
    openLicense: -1,
    image: "https://spoonacular.com/recipeImages/661531-556x370.jpg",
    imageType: "jpg",
    summary:
      'Steak with lemon and capers might be just the main course you are searching for. One serving contains <b>951 calories</b>, <b>47g of protein</b>, and <b>54g of fat</b>. For <b>$6.49 per serving</b>, this recipe <b>covers 32%</b> of your daily requirements of vitamins and minerals. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. 9 people were impressed by this recipe. It can be enjoyed any time, but it is especially good for <b>valentin day</b>. A mixture of flour, garlic, lemon wedges, and a handful of other ingredients are all it takes to make this recipe so flavorful. To use up the dry white wine you could follow this main course with the <a href="https://spoonacular.com/recipes/white-wine-frozen-yogurt-206235">White Wine Frozen Yogurt</a> as a dessert. All things considered, we decided this recipe <b>deserves a spoonacular score of 73%</b>. This score is pretty good. Similar recipes include <a href="https://spoonacular.com/recipes/steak-salad-sandwiches-with-capers-30072">Steak Salad Sandwiches with Capers</a>, <a href="https://spoonacular.com/recipes/steak-salad-with-arugula-parmesan-crispy-capers-8826">Steak Salad With Arugula, Parmesan & Crispy Capers</a>, and <a href="https://spoonacular.com/recipes/chicken-with-lemon-and-capers-29925">Chicken with Lemon and Capers</a>.',
    cuisines: [],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: [],
    occasions: ["valentine's day", "father's day"],
    instructions:
      "<ol><li>Flatten the steaks lightly with a meat mallet.</li><li>Combine flour, salt and pepper, dip steaks into the mixture, coating both sides.</li><li>Saut the steaks in a hot mixture of butter and olive oil over medium heat, about 4 minutes on each side. Remove from the pan and set aside.</li><li>Saut the garlic in the same fat for about 1 minute, stirring.</li><li>Add the wine and lemon juice, stir and simmer for 5 minutes to slightly reduce the liquid.</li><li>Add capers, stir. Return the steaks to the pan, cover and simmer over low heat for 4 minutes.</li></ol>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Flatten the steaks lightly with a meat mallet.",
            ingredients: [
              {
                id: 23232,
                name: "steak",
                localizedName: "steak",
                image: "ribeye-raw.jpg",
              },
              {
                id: 1065062,
                name: "meat",
                localizedName: "meat",
                image: "whole-chicken.jpg",
              },
            ],
            equipment: [
              {
                id: 3846,
                name: "meat tenderizer",
                localizedName: "meat tenderizer",
                image: "meat-mallet.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Combine flour, salt and pepper, dip steaks into the mixture, coating both sides.Saut the steaks in a hot mixture of butter and olive oil over medium heat, about 4 minutes on each side.",
            ingredients: [
              {
                id: 1102047,
                name: "salt and pepper",
                localizedName: "salt and pepper",
                image: "salt-and-pepper.jpg",
              },
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
              {
                id: 23232,
                name: "steak",
                localizedName: "steak",
                image: "ribeye-raw.jpg",
              },
              {
                id: 20081,
                name: "all purpose flour",
                localizedName: "all purpose flour",
                image: "flour.png",
              },
              {
                id: 0,
                name: "dip",
                localizedName: "dip",
                image: "",
              },
            ],
            equipment: [],
            length: {
              number: 4,
              unit: "minutes",
            },
          },
          {
            number: 3,
            step: "Remove from the pan and set aside.Saut the garlic in the same fat for about 1 minute, stirring.",
            ingredients: [
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
            length: {
              number: 1,
              unit: "minutes",
            },
          },
          {
            number: 4,
            step: "Add the wine and lemon juice, stir and simmer for 5 minutes to slightly reduce the liquid.",
            ingredients: [
              {
                id: 9152,
                name: "lemon juice",
                localizedName: "lemon juice",
                image: "lemon-juice.jpg",
              },
              {
                id: 14084,
                name: "wine",
                localizedName: "wine",
                image: "red-wine.jpg",
              },
            ],
            equipment: [],
            length: {
              number: 5,
              unit: "minutes",
            },
          },
          {
            number: 5,
            step: "Add capers, stir. Return the steaks to the pan, cover and simmer over low heat for 4 minutes.",
            ingredients: [
              {
                id: 2054,
                name: "capers",
                localizedName: "capers",
                image: "capers.jpg",
              },
              {
                id: 23232,
                name: "steak",
                localizedName: "steak",
                image: "ribeye-raw.jpg",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
            length: {
              number: 4,
              unit: "minutes",
            },
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/steak-with-lemon-and-capers-661531",
  },
];
export default popularData;
