const veganData = [
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 5,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 47,
    healthScore: 21,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 91.88,
    extendedIngredients: [
      {
        id: 9037,
        aisle: "Produce",
        image: "avocado.jpg",
        consistency: "SOLID",
        name: "avocados",
        nameClean: "avocado",
        original: "2 avocados, fairly soft, peeled and pit removed",
        originalName: "avocados, fairly soft, peeled and pit removed",
        amount: 2,
        unit: "",
        meta: ["soft", "peeled"],
        measures: {
          us: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 9160,
        aisle: "Produce",
        image: "lime-juice.png",
        consistency: "LIQUID",
        name: "lime juice",
        nameClean: "lime juice",
        original: "1 tablespoon lime juice",
        originalName: "lime juice",
        amount: 1,
        unit: "tablespoon",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
          metric: {
            amount: 1,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
        },
      },
      {
        id: 1002068,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "vinegar-(white).jpg",
        consistency: "LIQUID",
        name: "white wine vinegar",
        nameClean: "white wine vinegar",
        original: "¼ teaspoon white wine vinegar",
        originalName: "white wine vinegar",
        amount: 0.25,
        unit: "teaspoon",
        meta: ["white"],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 10011282,
        aisle: "Produce",
        image: "red-onion.png",
        consistency: "SOLID",
        name: "red onion",
        nameClean: "red onion",
        original: "½ red onion, minced",
        originalName: "red onion, minced",
        amount: 0.5,
        unit: "",
        meta: ["red", "minced"],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 0.5,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 11977,
        aisle: "Produce",
        image: "serrano-pepper.jpg",
        consistency: "SOLID",
        name: "serrano pepper",
        nameClean: "serrano pepper",
        original: "1 Serrano pepper, minced",
        originalName: "Serrano pepper, minced",
        amount: 1,
        unit: "",
        meta: ["minced"],
        measures: {
          us: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 11165,
        aisle: "Produce;Spices and Seasonings",
        image: "cilantro.png",
        consistency: "SOLID",
        name: "cilantro",
        nameClean: "cilantro",
        original: "2 tablespoons chopped cilantro",
        originalName: "chopped cilantro",
        amount: 2,
        unit: "tablespoons",
        meta: ["chopped"],
        measures: {
          us: {
            amount: 2,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 2,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 10211529,
        aisle: "Produce",
        image: "roma-tomatoes.png",
        consistency: "SOLID",
        name: "roma tomato",
        nameClean: "italian tomato",
        original: "1 roma tomato, pulp removed, then diced",
        originalName: "roma tomato, pulp removed, then diced",
        amount: 1,
        unit: "",
        meta: ["diced"],
        measures: {
          us: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 2047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "SOLID",
        name: "salt",
        nameClean: "table salt",
        original: "½ teaspoon salt",
        originalName: "salt",
        amount: 0.5,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 1002030,
        aisle: "Spices and Seasonings",
        image: "pepper.jpg",
        consistency: "SOLID",
        name: "black pepper",
        nameClean: "black pepper",
        original: "¼ teaspoon freshly ground black pepper",
        originalName: "freshly ground black pepper",
        amount: 0.25,
        unit: "teaspoon",
        meta: ["black", "freshly ground"],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 1002014,
        aisle: "Spices and Seasonings",
        image: "ground-cumin.jpg",
        consistency: "SOLID",
        name: "cumin",
        nameClean: "cumin",
        original: "1/8 teaspoon cumin",
        originalName: "cumin",
        amount: 0.125,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: {
            amount: 0.125,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.125,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 1022020,
        aisle: "Spices and Seasonings",
        image: "garlic-powder.png",
        consistency: "SOLID",
        name: "garlic powder",
        nameClean: "garlic powder",
        original: "1/8 teaspoon garlic powder",
        originalName: "garlic powder",
        amount: 0.125,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: {
            amount: 0.125,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.125,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
    ],
    id: 661188,
    title: "Spicy Seasoned Loaded Guacamole",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      "https://www.foodista.com/recipe/Z7GWGX8D/spicy-seasoned-loaded-guacamole",
    openLicense: -1,
    image: "https://spoonacular.com/recipeImages/661188-556x370.jpg",
    imageType: "jpg",
    summary:
      'Spicy Seasoned Loaded Guacamole might be just the hor d\'oeuvre you are searching for. This recipe makes 4 servings with <b>171 calories</b>, <b>2g of protein</b>, and <b>15g of fat</b> each. For <b>92 cents per serving</b>, this recipe <b>covers 9%</b> of your daily requirements of vitamins and minerals. If you have roma tomato, cumin, pepper, and a few other ingredients on hand, you can make it. 47 people found this recipe to be scrumptious and satisfying. It is a <b>very reasonably priced</b> recipe for fans of Mexican food. It is brought to you by Foodista. From preparation to the plate, this recipe takes roughly <b>roughly 45 minutes</b>. It is a good option if you\'re following a <b>gluten free, dairy free, lacto ovo vegetarian, and whole 30</b> diet. Overall, this recipe earns a <b>solid spoonacular score of 79%</b>. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/loaded-guacamole-tacos-874139">Loaded Guacamole Tacos</a>, <a href="https://spoonacular.com/recipes/loaded-guacamole-nachos-610053">Loaded Guacamole Nachos</a>, and <a href="https://spoonacular.com/recipes/fully-loaded-guacamole-621631">Fully Loaded Guacamole</a>.',
    cuisines: [],
    dishTypes: [
      "antipasti",
      "condiment",
      "starter",
      "snack",
      "appetizer",
      "dip",
      "antipasto",
      "hor d'oeuvre",
      "spread",
    ],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "lacto ovo vegetarian",
      "primal",
      "whole 30",
      "vegan",
    ],
    occasions: [],
    instructions:
      "In a medium bowl, mash avocado and mix with lime juice and vinegar.\nStir in the salt, pepper, cumin, and garlic powder.\nMix in red onion, Serrano pepper, cilantro, and chopped tomato.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "In a medium bowl, mash avocado and mix with lime juice and vinegar.",
            ingredients: [
              {
                id: 9160,
                name: "lime juice",
                localizedName: "lime juice",
                image: "lime-juice.png",
              },
              {
                id: 9037,
                name: "avocado",
                localizedName: "avocado",
                image: "avocado.jpg",
              },
              {
                id: 2053,
                name: "vinegar",
                localizedName: "vinegar",
                image: "vinegar-(white).jpg",
              },
            ],
            equipment: [
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "bowl.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Stir in the salt, pepper, cumin, and garlic powder.",
            ingredients: [
              {
                id: 1022020,
                name: "garlic powder",
                localizedName: "garlic powder",
                image: "garlic-powder.png",
              },
              {
                id: 1002030,
                name: "pepper",
                localizedName: "pepper",
                image: "pepper.jpg",
              },
              {
                id: 1002014,
                name: "cumin",
                localizedName: "cumin",
                image: "ground-cumin.jpg",
              },
              {
                id: 2047,
                name: "salt",
                localizedName: "salt",
                image: "salt.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "Mix in red onion, Serrano pepper, cilantro, and chopped tomato.",
            ingredients: [
              {
                id: 11977,
                name: "serrano pepper",
                localizedName: "serrano pepper",
                image: "serrano-pepper.jpg",
              },
              {
                id: 10011282,
                name: "red onion",
                localizedName: "red onion",
                image: "red-onion.png",
              },
              {
                id: 11165,
                name: "cilantro",
                localizedName: "cilantro",
                image: "cilantro.png",
              },
              {
                id: 11529,
                name: "tomato",
                localizedName: "tomato",
                image: "tomato.png",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/spicy-seasoned-loaded-guacamole-661188",
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 3,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 7,
    healthScore: 2,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 36.99,
    extendedIngredients: [
      {
        id: 2009,
        aisle: "Spices and Seasonings",
        image: "chili-powder.jpg",
        consistency: "SOLID",
        name: "chili powder",
        nameClean: "chili powder",
        original: "1/4 teaspoon hot or mild chili powder",
        originalName: "hot or mild chili powder",
        amount: 0.25,
        unit: "teaspoon",
        meta: ["hot"],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 11165,
        aisle: "Produce;Spices and Seasonings",
        image: "cilantro.png",
        consistency: "SOLID",
        name: "fresh cilantro",
        nameClean: "cilantro",
        original: "2 cups fresh cilantro, chopped",
        originalName: "fresh cilantro, chopped",
        amount: 2,
        unit: "cups",
        meta: ["fresh", "chopped"],
        measures: {
          us: {
            amount: 2,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 473.176,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "SOLID",
        name: "garlic",
        nameClean: "garlic",
        original: "3 cloves garlic, thinly sliced",
        originalName: "garlic, thinly sliced",
        amount: 3,
        unit: "cloves",
        meta: ["thinly sliced"],
        measures: {
          us: {
            amount: 3,
            unitShort: "cloves",
            unitLong: "cloves",
          },
          metric: {
            amount: 3,
            unitShort: "cloves",
            unitLong: "cloves",
          },
        },
      },
      {
        id: 4053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "LIQUID",
        name: "olive oil",
        nameClean: "olive oil",
        original: "1/4 cup olive oil",
        originalName: "olive oil",
        amount: 0.25,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 59.147,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 12014,
        aisle: "Savory Snacks",
        image: "pumpkin-seeds.jpg",
        consistency: "SOLID",
        name: "pepitas",
        nameClean: "pumpkin seeds",
        original: "1/4 cup pepitas (pumpkin seeds)",
        originalName: "pepitas (pumpkin seeds)",
        amount: 0.25,
        unit: "cup",
        meta: ["(pumpkin seeds)"],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 59.147,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 1012047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "SOLID",
        name: "sea salt",
        nameClean: "coarse sea salt",
        original: "1/2 teaspoon sea salt",
        originalName: "sea salt",
        amount: 0.5,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
    ],
    id: 661066,
    title: "Spicy Cilantro Pesto",
    readyInMinutes: 45,
    servings: 6,
    sourceUrl: "http://www.foodista.com/recipe/SY3DS4WZ/spicy-cilantro-pesto",
    openLicense: -1,
    image: "https://spoonacular.com/recipeImages/661066-556x370.jpg",
    imageType: "jpg",
    summary:
      'Spicy Cilantro Pesto might be just the condiment you are searching for. This recipe makes 6 servings with <b>98 calories</b>, <b>1g of protein</b>, and <b>10g of fat</b> each. For <b>39 cents per serving</b>, this recipe <b>covers 3%</b> of your daily requirements of vitamins and minerals. This recipe from Foodista has 7 fans. If you have sea salt, cilantro, garlic, and a few other ingredients on hand, you can make it. It is a good option if you\'re following a <b>caveman, gluten free, primal, and whole 30</b> diet. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 30%</b>. This score is rather bad. Similar recipes include <a href="https://spoonacular.com/recipes/spicy-cilantromarcona-almond-pesto-145171">Spicy Cilantro&ndash;Marconan Almond Pesto</a>, <a href="https://spoonacular.com/recipes/cilantro-pesto-cilantro-yogurt-sauce-532912">Cilantro Pesto & Cilantro Yogurt Sauce</a>, and <a href="https://spoonacular.com/recipes/tilapia-with-cilantro-pesto-tilapia-a-la-plancha-con-pesto-de-cilantro-226365">TILAPIA WITH CILANTRO PESTO (TILAPIAn A LA PLANCHA CON PESTO DE CILANTRO)</a>.',
    cuisines: [],
    dishTypes: ["side dish"],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "lacto ovo vegetarian",
      "primal",
      "whole 30",
      "vegan",
    ],
    occasions: [],
    instructions:
      "<ol><li>Place cilantro in food processor. Pulse until well chopped. Add garlic, sea salt, pepitas, and chili powder. Chop well.</li><li>Using an attachment for adding liquids, add olive oil drop by drop to the running food processor to form a thick paste. Scoop paste into pint jars and store in fridge or freezer.</li></ol>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Place cilantro in food processor. Pulse until well chopped.",
            ingredients: [
              {
                id: 11165,
                name: "cilantro",
                localizedName: "cilantro",
                image: "cilantro.png",
              },
            ],
            equipment: [
              {
                id: 404771,
                name: "food processor",
                localizedName: "food processor",
                image: "food-processor.png",
              },
            ],
          },
          {
            number: 2,
            step: "Add garlic, sea salt, pepitas, and chili powder. Chop well.Using an attachment for adding liquids, add olive oil drop by drop to the running food processor to form a thick paste. Scoop paste into pint jars and store in fridge or freezer.",
            ingredients: [
              {
                id: 2009,
                name: "chili powder",
                localizedName: "chili powder",
                image: "chili-powder.jpg",
              },
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
              {
                id: 1012047,
                name: "sea salt",
                localizedName: "sea salt",
                image: "salt.jpg",
              },
              {
                id: 12014,
                name: "pumpkin seeds",
                localizedName: "pumpkin seeds",
                image: "pumpkin-seeds.jpg",
              },
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
            ],
            equipment: [
              {
                id: 404771,
                name: "food processor",
                localizedName: "food processor",
                image: "food-processor.png",
              },
            ],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl: "https://spoonacular.com/spicy-cilantro-pesto-661066",
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 12,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 6,
    healthScore: 7,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 214.6,
    extendedIngredients: [
      {
        id: 10014412,
        aisle: "Frozen",
        image: "ice-cubes.png",
        consistency: "SOLID",
        name: "ice",
        nameClean: "ice",
        original: "3 cups of ice",
        originalName: "ice",
        amount: 3,
        unit: "cups",
        meta: [],
        measures: {
          us: {
            amount: 3,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 709.764,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 9273,
        aisle: "Beverages",
        image: "pineapple-juice.jpg",
        consistency: "LIQUID",
        name: "pineapple juice",
        nameClean: "pineapple juice",
        original: "2 1/2 cups pineapple juice",
        originalName: "pineapple juice",
        amount: 2.5,
        unit: "cups",
        meta: [],
        measures: {
          us: {
            amount: 2.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 591.47,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 12118,
        aisle: "Canned and Jarred;Milk, Eggs, Other Dairy",
        image: "coconut-milk.png",
        consistency: "LIQUID",
        name: "coconut milk",
        nameClean: "coconut milk",
        original: "1/2 cup coconut milk",
        originalName: "coconut milk",
        amount: 0.5,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 118.294,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 10314037,
        aisle: "Alcoholic Beverages",
        image: "white-rum.jpg",
        consistency: "LIQUID",
        name: "coconut rum",
        nameClean: "coconut rum",
        original: "1/2 cup coconut rum",
        originalName: "coconut rum",
        amount: 0.5,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 118.294,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 9266,
        aisle: "Produce",
        image: "pineapple.jpg",
        consistency: "SOLID",
        name: "pineapple",
        nameClean: "pineapple",
        original: "pineapple",
        originalName: "pineapple",
        amount: 3,
        unit: "servings",
        meta: [],
        measures: {
          us: {
            amount: 3,
            unitShort: "servings",
            unitLong: "servings",
          },
          metric: {
            amount: 3,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
      {
        id: 9328,
        aisle: "Canned and Jarred",
        image: "maraschino.jpg",
        consistency: "SOLID",
        name: "maraschino cherries",
        nameClean: "maraschino cherries",
        original: "maraschino cherries for garnish",
        originalName: "maraschino cherries for garnish",
        amount: 3,
        unit: "servings",
        meta: ["for garnish"],
        measures: {
          us: {
            amount: 3,
            unitShort: "servings",
            unitLong: "servings",
          },
          metric: {
            amount: 3,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
    ],
    id: 1098357,
    title: "Three Ingredient Frozen Pina Colada",
    readyInMinutes: 5,
    servings: 3,
    sourceUrl:
      "https://www.foodista.com/recipe/DFG678TL/three-ingredient-frozen-pina-colada",
    openLicense: -1,
    image: "https://spoonacular.com/recipeImages/1098357-556x370.jpg",
    imageType: "jpg",
    summary:
      'Need a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan beverage</b>? Three Ingredient Frozen Pina Colada could be a super recipe to try. One serving contains <b>320 calories</b>, <b>2g of protein</b>, and <b>8g of fat</b>. This recipe serves 3. For <b>$2.15 per serving</b>, this recipe <b>covers 12%</b> of your daily requirements of vitamins and minerals. 1 person has tried and liked this recipe. It is brought to you by Foodista. Head to the store and pick up maraschino cherries, pineapple juice, coconut milk, and a few other things to make it today. This recipe is typical of Mexican cuisine. From preparation to the plate, this recipe takes approximately <b>5 minutes</b>. Taking all factors into account, this recipe <b>earns a spoonacular score of 46%</b>, which is solid. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/pia-colada-frozen-dessert-174015">Piña Colada Frozen Dessert</a>, <a href="https://spoonacular.com/recipes/pina-colada-frozen-yogurt-586418">Pina Colada Frozen Yogurt</a>, and <a href="https://spoonacular.com/recipes/frozen-pina-colada-cake-795393">Frozen Pina Colada Cake</a>.',
    cuisines: [],
    dishTypes: ["beverage", "drink"],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    occasions: [],
    instructions:
      "<ol><li>Add ice, pineapple juice, coconut milk, and rum to the blender.</li><li>Blend until smooth and creamy.</li><li>Serve with fresh pineapple wedges and cherry garnish.</li></ol>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Add ice, pineapple juice, coconut milk, and rum to the blender.Blend until smooth and creamy.",
            ingredients: [
              {
                id: 9273,
                name: "pineapple juice",
                localizedName: "pineapple juice",
                image: "pineapple-juice.jpg",
              },
              {
                id: 12118,
                name: "coconut milk",
                localizedName: "coconut milk",
                image: "coconut-milk.png",
              },
              {
                id: 10014412,
                name: "ice",
                localizedName: "ice",
                image: "ice-cubes.png",
              },
              {
                id: 11114037,
                name: "rum",
                localizedName: "rum",
                image: "rum-dark.jpg",
              },
            ],
            equipment: [
              {
                id: 404726,
                name: "blender",
                localizedName: "blender",
                image: "blender.png",
              },
            ],
          },
          {
            number: 2,
            step: "Serve with fresh pineapple wedges and cherry garnish.",
            ingredients: [
              {
                id: 9266,
                name: "pineapple",
                localizedName: "pineapple",
                image: "pineapple.jpg",
              },
              {
                id: 9070,
                name: "cherries",
                localizedName: "cherries",
                image: "cherries.jpg",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/three-ingredient-frozen-pina-colada-1098357",
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: true,
    weightWatcherSmartPoints: 6,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 11,
    healthScore: 1,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 60.44,
    extendedIngredients: [
      {
        id: 9316,
        aisle: "Produce",
        image: "strawberries.png",
        consistency: "SOLID",
        name: "strawberries",
        nameClean: "strawberries",
        original: "1 1/2 cups strawberries, stems removed and sliced",
        originalName: "strawberries, stems removed and sliced",
        amount: 1.5,
        unit: "cups",
        meta: ["sliced"],
        measures: {
          us: {
            amount: 1.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 354.882,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 19335,
        aisle: "Baking",
        image: "sugar-in-bowl.png",
        consistency: "SOLID",
        name: "sugar",
        nameClean: "sugar",
        original: "1/2 cup sugar",
        originalName: "sugar",
        amount: 0.5,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 118.294,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 14144,
        aisle: "Beverages",
        image: "soda-can.jpg",
        consistency: "SOLID",
        name: "lemon lime soda",
        nameClean: "lemon lime pop",
        original: "1 30ml lemon lime soda (I used about 1/4 of a liter)",
        originalName: "lemon lime soda (I used about 1/4 of a liter)",
        amount: 30,
        unit: "ml",
        meta: ["(I used)"],
        measures: {
          us: {
            amount: 1.015,
            unitShort: "fl. oz",
            unitLong: "fl. oz",
          },
          metric: {
            amount: 30,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 14121,
        aisle: "Beverages",
        image: "sparkling-water.png",
        consistency: "LIQUID",
        name: "seltzer",
        nameClean: "sparkling water",
        original:
          "2 30ml seltzer (preferably lemon lime seltzer, if not add a couple extra tbsp lime juice)",
        originalName:
          "seltzer (preferably lemon lime seltzer, if not add a couple extra tbsp lime juice)",
        amount: 60,
        unit: "ml",
        meta: [
          "(preferably lemon lime seltzer, if not add a couple extra tbsp lime juice)",
        ],
        measures: {
          us: {
            amount: 2.029,
            unitShort: "fl. oz",
            unitLong: "fl. ozs",
          },
          metric: {
            amount: 60,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 19908,
        aisle: "Health Foods;Baking",
        image: "raw-brown-sugar.png",
        consistency: "SOLID",
        name: "turbinado sugar",
        nameClean: "turbinado sugar",
        original: "turbinado sugar, optional for rimming glasses",
        originalName: "turbinado sugar, optional for rimming glasses",
        amount: 1,
        unit: "serving",
        meta: ["for rimming glasses"],
        measures: {
          us: {
            amount: 1,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
      {
        id: 9160,
        aisle: "Produce",
        image: "lime-juice.png",
        consistency: "LIQUID",
        name: "juice of lime",
        nameClean: "lime juice",
        original: "juice from 1 lime",
        originalName: "juice from lime",
        amount: 1,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 9159,
        aisle: "Produce",
        image: "lime.jpg",
        consistency: "SOLID",
        name: "limes",
        nameClean: "lime",
        original: "limes, sliced for garnish",
        originalName: "limes, sliced for garnish",
        amount: 1,
        unit: "serving",
        meta: ["sliced", "for garnish"],
        measures: {
          us: {
            amount: 1,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
      {
        id: 10014412,
        aisle: "Frozen",
        image: "ice-cubes.png",
        consistency: "SOLID",
        name: "ice",
        nameClean: "ice",
        original: "ice",
        originalName: "ice",
        amount: 1,
        unit: "serving",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
    ],
    id: 658152,
    title: "Refreshing Strawberry Limeade",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      "https://www.foodista.com/recipe/26NF6ZNY/refreshing-strawberry-limeade",
    openLicense: -1,
    image: "https://spoonacular.com/recipeImages/658152-556x370.jpg",
    imageType: "jpg",
    summary:
      'You can never have too many Mexican recipes, so give Refreshing Strawberry Limeade a try. This recipe serves 4 and costs 60 cents per serving. This beverage has <b>121 calories</b>, <b>0g of protein</b>, and <b>0g of fat</b> per serving. This recipe is liked by 11 foodies and cooks. It is brought to you by Foodista. It will be a hit at your <b>Mother\'s Day</b> event. It is a good option if you\'re following a <b>gluten free, dairy free, lacto ovo vegetarian, and fodmap friendly</b> diet. If you have ice, sugar, lemon lime soda, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes roughly <b>roughly 45 minutes</b>. With a spoonacular <b>score of 24%</b>, this dish is rather bad. <a href="https://spoonacular.com/recipes/strawberry-limeade-768774">Strawberry Limeade</a>, <a href="https://spoonacular.com/recipes/strawberry-limeade-472460">Strawberry Limeade</a>, and <a href="https://spoonacular.com/recipes/strawberry-limeade-margaritas-765529">Strawberry Limeade Margaritas</a> are very similar to this recipe.',
    cuisines: [],
    dishTypes: ["beverage", "drink"],
    diets: [
      "gluten free",
      "dairy free",
      "lacto ovo vegetarian",
      "fodmap friendly",
      "vegan",
    ],
    occasions: ["mother's day"],
    instructions:
      "Add berries and sugar to a bowl and let macerate for about 30 minutes.\nAdd berries to a food processor (or blender) and pulse until smooth.\nIn a large pitcher add ice (about 1/3 of the way), then top with 2 parts seltzer to one part lemon lime soda.\nStir in a few scoops of strawberry puree and add juice from 1 lime.\nStir well then taste. Add more strawberry and lime juice if needed.\nI add thinly slice lime to the pitcher and garnish the glasses with lime wedges and a sugared rim.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Add berries and sugar to a bowl and let macerate for about 30 minutes.",
            ingredients: [
              {
                id: 1009054,
                name: "berries",
                localizedName: "berries",
                image: "berries-mixed.jpg",
              },
              {
                id: 19335,
                name: "sugar",
                localizedName: "sugar",
                image: "sugar-in-bowl.png",
              },
            ],
            equipment: [
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "bowl.jpg",
              },
            ],
            length: {
              number: 30,
              unit: "minutes",
            },
          },
          {
            number: 2,
            step: "Add berries to a food processor (or blender) and pulse until smooth.",
            ingredients: [
              {
                id: 1009054,
                name: "berries",
                localizedName: "berries",
                image: "berries-mixed.jpg",
              },
            ],
            equipment: [
              {
                id: 404771,
                name: "food processor",
                localizedName: "food processor",
                image: "food-processor.png",
              },
              {
                id: 404726,
                name: "blender",
                localizedName: "blender",
                image: "blender.png",
              },
            ],
          },
          {
            number: 3,
            step: "In a large pitcher add ice (about 1/3 of the way), then top with 2 parts seltzer to one part lemon lime soda.",
            ingredients: [
              {
                id: 14144,
                name: "lemon lime pop",
                localizedName: "lemon lime pop",
                image: "soda-can.jpg",
              },
              {
                id: 14121,
                name: "sparkling water",
                localizedName: "sparkling water",
                image: "sparkling-water.png",
              },
              {
                id: 10014412,
                name: "ice",
                localizedName: "ice",
                image: "ice-cubes.png",
              },
            ],
            equipment: [],
          },
          {
            number: 4,
            step: "Stir in a few scoops of strawberry puree and add juice from 1 lime.",
            ingredients: [
              {
                id: 1009316,
                name: "strawberry puree",
                localizedName: "strawberry puree",
                image: "strawberry-sauce.png",
              },
              {
                id: 1019016,
                name: "juice",
                localizedName: "juice",
                image: "apple-juice.jpg",
              },
              {
                id: 9159,
                name: "lime",
                localizedName: "lime",
                image: "lime.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 5,
            step: "Stir well then taste.",
            ingredients: [],
            equipment: [],
          },
          {
            number: 6,
            step: "Add more strawberry and lime juice if needed.",
            ingredients: [
              {
                id: 9160,
                name: "lime juice",
                localizedName: "lime juice",
                image: "lime-juice.png",
              },
              {
                id: 9316,
                name: "strawberries",
                localizedName: "strawberries",
                image: "strawberries.png",
              },
            ],
            equipment: [],
          },
          {
            number: 7,
            step: "I add thinly slice lime to the pitcher and garnish the glasses with lime wedges and a sugared rim.",
            ingredients: [
              {
                id: 1029159,
                name: "lime wedge",
                localizedName: "lime wedge",
                image: "lime-wedge.jpg",
              },
              {
                id: 9159,
                name: "lime",
                localizedName: "lime",
                image: "lime.jpg",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/refreshing-strawberry-limeade-658152",
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 4,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 6,
    healthScore: 13,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 292.22,
    extendedIngredients: [
      {
        id: 9326,
        aisle: "Produce",
        image: "watermelon.png",
        consistency: "SOLID",
        name: "watermelon cubes",
        nameClean: "watermelon",
        original: "1 blenderful of chilled watermelon cubes",
        originalName: "blenderful of chilled watermelon cubes",
        amount: 1,
        unit: "",
        meta: ["chilled"],
        measures: {
          us: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 9159,
        aisle: "Produce",
        image: "lime.jpg",
        consistency: "SOLID",
        name: "limes",
        nameClean: "lime",
        original: "2 limes, wedged",
        originalName: "limes, wedged",
        amount: 2,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 1002044,
        aisle: "Produce",
        image: "lemon-basil.jpg",
        consistency: "SOLID",
        name: "herbs",
        nameClean: "lemon basil",
        original: "1 bunch of leafy herbs (think: mint, basil, cilantro)",
        originalName: "leafy herbs (think: mint, basil, cilantro)",
        amount: 1,
        unit: "bunch",
        meta: ["(think: mint, basil, cilantro)"],
        measures: {
          us: {
            amount: 1,
            unitShort: "bunch",
            unitLong: "bunch",
          },
          metric: {
            amount: 1,
            unitShort: "bunch",
            unitLong: "bunch",
          },
        },
      },
      {
        id: 11979,
        aisle: "Canned and Jarred;Produce;Ethnic Foods",
        image: "jalapeno-pepper.png",
        consistency: "SOLID",
        name: "jalapeno peppers",
        nameClean: "jalapeno pepper",
        original: "2 jalapeño peppers, deseeded",
        originalName: "jalapeño peppers, deseeded",
        amount: 2,
        unit: "",
        meta: ["deseeded"],
        measures: {
          us: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 14121,
        aisle: "Beverages",
        image: "sparkling-water.png",
        consistency: "LIQUID",
        name: "club soda",
        nameClean: "sparkling water",
        original: "2 cups of club soda",
        originalName: "club soda",
        amount: 2,
        unit: "cups",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 473.176,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 14037,
        aisle: "Alcoholic Beverages",
        image: "rum-dark.jpg",
        consistency: "SOLID",
        name: "liquor",
        nameClean: "alcohol",
        original:
          "12 ounces Liquor, approximately (think: gin, tequila, rum, simple syrup to taste ice cubes",
        originalName:
          "Liquor, approximately (think: gin, tequila, rum, simple syrup to taste ice cubes",
        amount: 12,
        unit: "ounces",
        meta: ["to taste"],
        measures: {
          us: {
            amount: 12,
            unitShort: "oz",
            unitLong: "ounces",
          },
          metric: {
            amount: 340.194,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 90480,
        aisle: "Alcoholic Beverages",
        image: "simple-syrup.jpg",
        consistency: "LIQUID",
        name: "simple syrup",
        nameClean: "simple syrup",
        original: "simple syrup to taste",
        originalName: "simple syrup to taste",
        amount: 1,
        unit: "serving",
        meta: ["to taste"],
        measures: {
          us: {
            amount: 1,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
      {
        id: 10014412,
        aisle: "Frozen",
        image: "ice-cubes.png",
        consistency: "SOLID",
        name: "ice cubes",
        nameClean: "ice",
        original: "ice cubes",
        originalName: "ice cubes",
        amount: 1,
        unit: "serving",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
      {
        id: 9326,
        aisle: "Produce",
        image: "watermelon.png",
        consistency: "SOLID",
        name: "watermelon",
        nameClean: "watermelon",
        original:
          "1Whiz the chilled watermelon in a blender and strain for a smoother cocktail to serve on ice. For a frozen variation, freeze some watermelon cubes and blend it in with the chilled watermelon.",
        originalName:
          "1Whiz the chilled watermelon in a blender and strain for a smoother cocktail to serve on ice. For a frozen variation, freeze some watermelon cubes and blend it in with the chilled watermelon",
        amount: 1,
        unit: "serving",
        meta: [
          "frozen",
          "with the chilled watermelon.",
          "chilled",
          "for a smoother cocktail to serve on ice. for a  variation, freeze some watermelon cubes and blend it in ",
        ],
        measures: {
          us: {
            amount: 1,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
      {
        id: 99105,
        aisle: "Produce",
        image: "bottle-gourd.jpg",
        consistency: "SOLID",
        name: "bottle gourd",
        nameClean: "bottle gourd",
        original:
          "2In a large pitcher, muddle 1 lime, herb leaves, and 1-2 jalapeños. Use a rolling pin or the bottom of a glass bottle if you don't have a muddler.",
        originalName:
          "2In a pitcher, muddle 1 lime, herb leaves, and 1-2 jalapeños. Use a rolling pin or the bottom of a glass bottle if you don't have a muddler",
        amount: 1,
        unit: "large",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "large",
            unitLong: "large",
          },
          metric: {
            amount: 1,
            unitShort: "large",
            unitLong: "large",
          },
        },
      },
      {
        id: 9326,
        aisle: "Produce",
        image: "watermelon.png",
        consistency: "SOLID",
        name: "watermelon",
        nameClean: "watermelon",
        original:
          "3Stir in the blended watermelon, liquor, 1 tablespoon soda, and sweeten to taste.",
        originalName:
          "3Stir in the blended watermelon, liquor, soda, and sweeten to taste",
        amount: 1,
        unit: "tablespoon",
        meta: ["to taste"],
        measures: {
          us: {
            amount: 1,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
          metric: {
            amount: 1,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
        },
      },
      {
        id: 10014412,
        aisle: "Frozen",
        image: "ice-cubes.png",
        consistency: "SOLID",
        name: "ice",
        nameClean: "ice",
        original:
          "4Serve in ice-filled glasses and garnish with lime wedges, herbs, and jalapeño slices.",
        originalName:
          "4Serve in ice-filled and garnish with lime wedges, herbs, and jalapeño slices",
        amount: 1,
        unit: "glasses",
        meta: ["with lime wedges, herbs, and jalapeño slices."],
        measures: {
          us: {
            amount: 1,
            unitShort: "glasses",
            unitLong: "glasses",
          },
          metric: {
            amount: 1,
            unitShort: "glasses",
            unitLong: "glasses",
          },
        },
      },
    ],
    id: 665016,
    title: "Watermelon Jalapeño Cocktail Cooler",
    readyInMinutes: 45,
    servings: 6,
    sourceUrl:
      "https://www.foodista.com/recipe/5JF2LB3S/watermelon-jalapeno-cocktail-cooler",
    openLicense: -1,
    image: "https://spoonacular.com/recipeImages/665016-556x370.jpg",
    imageType: "jpg",
    summary:
      'Watermelon Jalapeño Cocktail Cooler might be a good recipe to expand your beverage repertoire. This recipe serves 6. For <b>$2.92 per serving</b>, this recipe <b>covers 17%</b> of your daily requirements of vitamins and minerals. Watching your figure? This gluten free, dairy free, lacto ovo vegetarian, and vegan recipe has <b>380 calories</b>, <b>5g of protein</b>, and <b>1g of fat</b> per serving. 6 people were glad they tried this recipe. It will be a hit at your <b>Summer</b> event. A mixture of whiz the watermelon in a blender and strain, jalapeño peppers, ice cubes, and a handful of other ingredients are all it takes to make this recipe so yummy. From preparation to the plate, this recipe takes approximately <b>approximately 45 minutes</b>. It is brought to you by Foodista. Taking all factors into account, this recipe <b>earns a spoonacular score of 53%</b>, which is solid. <a href="https://spoonacular.com/recipes/watermelon-cooler-516082">Watermelon Cooler</a>, <a href="https://spoonacular.com/recipes/watermelon-cooler-225155">Watermelon Cooler</a>, and <a href="https://spoonacular.com/recipes/watermelon-cooler-27668">Watermelon Cooler</a> are very similar to this recipe.',
    cuisines: [],
    dishTypes: ["beverage", "drink"],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    occasions: ["summer"],
    instructions:
      "Whiz the chilled watermelon in a blender and strain for a smoother cocktail to serve on ice. For a frozen variation, freeze some watermelon cubes and blend it in with the chilled watermelon.\nIn a large pitcher, muddle 1 lime, herb leaves, and 1-2 jalapeos. Use a rolling pin or the bottom of a glass bottle if you dont have a muddler.\nStir in the blended watermelon, liquor, a splash of soda, and sweeten to taste.\nServe in ice-filled glasses and garnish with lime wedges, herbs, and jalapeo slices.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Whiz the chilled watermelon in a blender and strain for a smoother cocktail to serve on ice. For a frozen variation, freeze some watermelon cubes and blend it in with the chilled watermelon.",
            ingredients: [
              {
                id: 9326,
                name: "watermelon",
                localizedName: "watermelon",
                image: "watermelon.png",
              },
              {
                id: 0,
                name: "cocktail",
                localizedName: "cocktail",
                image: "rum-dark.jpg",
              },
              {
                id: 10014412,
                name: "ice",
                localizedName: "ice",
                image: "ice-cubes.png",
              },
            ],
            equipment: [
              {
                id: 404726,
                name: "blender",
                localizedName: "blender",
                image: "blender.png",
              },
            ],
          },
          {
            number: 2,
            step: "In a large pitcher, muddle 1 lime, herb leaves, and 1-2 jalapeos. Use a rolling pin or the bottom of a glass bottle if you dont have a muddler.",
            ingredients: [
              {
                id: 9159,
                name: "lime",
                localizedName: "lime",
                image: "lime.jpg",
              },
            ],
            equipment: [
              {
                id: 404746,
                name: "rolling pin",
                localizedName: "rolling pin",
                image: "rolling-pin.jpg",
              },
            ],
          },
          {
            number: 3,
            step: "Stir in the blended watermelon, liquor, a splash of soda, and sweeten to taste.",
            ingredients: [
              {
                id: 9326,
                name: "watermelon",
                localizedName: "watermelon",
                image: "watermelon.png",
              },
              {
                id: 14037,
                name: "liquor",
                localizedName: "liquor",
                image: "rum-dark.jpg",
              },
              {
                id: 0,
                name: "pop",
                localizedName: "soft drink",
                image: "",
              },
            ],
            equipment: [],
          },
          {
            number: 4,
            step: "Serve in ice-filled glasses and garnish with lime wedges, herbs, and jalapeo slices.",
            ingredients: [
              {
                id: 1029159,
                name: "lime wedge",
                localizedName: "lime wedge",
                image: "lime-wedge.jpg",
              },
              {
                id: 1002044,
                name: "herbs",
                localizedName: "herbs",
                image: "mixed-fresh-herbs.jpg",
              },
              {
                id: 10014412,
                name: "ice",
                localizedName: "ice",
                image: "ice-cubes.png",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/watermelon-jalapeo-cocktail-cooler-665016",
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: true,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 4,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 3689,
    healthScore: 76,
    creditsText: "Full Belly Sisters",
    license: "CC BY-SA 3.0",
    sourceName: "Full Belly Sisters",
    pricePerServing: 112.39,
    extendedIngredients: [
      {
        id: 11090,
        aisle: "Produce",
        image: "broccoli.jpg",
        consistency: "SOLID",
        name: "broccoli",
        nameClean: "broccoli",
        original: "2 cups cooked broccoli, chopped small",
        originalName: "cooked broccoli, chopped small",
        amount: 2,
        unit: "cups",
        meta: ["cooked", "chopped"],
        measures: {
          us: {
            amount: 2,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 473.176,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 11135,
        aisle: "Produce",
        image: "cauliflower.jpg",
        consistency: "SOLID",
        name: "cauliflower",
        nameClean: "cauliflower",
        original: "1 head of cauliflower, raw",
        originalName: "cauliflower, raw",
        amount: 1,
        unit: "head",
        meta: ["raw"],
        measures: {
          us: {
            amount: 1,
            unitShort: "head",
            unitLong: "head",
          },
          metric: {
            amount: 1,
            unitShort: "head",
            unitLong: "head",
          },
        },
      },
      {
        id: 4047,
        aisle: "Health Foods;Baking",
        image: "oil-coconut.jpg",
        consistency: "LIQUID",
        name: "coconut oil",
        nameClean: "coconut oil",
        original: "1 + 1 T coconut oil or butter",
        originalName: "1 T coconut oil or butter",
        amount: 1,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 20041,
        aisle: "Pasta and Rice",
        image: "rice-brown-cooked.png",
        consistency: "SOLID",
        name: "cooked brown rice",
        nameClean: "cooked brown rice",
        original: "3 cups of cooked brown rice, cold",
        originalName: "cooked brown rice, cold",
        amount: 3,
        unit: "cups",
        meta: ["cold", "cooked"],
        measures: {
          us: {
            amount: 3,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 709.764,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "SOLID",
        name: "garlic",
        nameClean: "garlic",
        original: "5 cloves of garlic, chopped",
        originalName: "garlic, chopped",
        amount: 5,
        unit: "cloves",
        meta: ["chopped"],
        measures: {
          us: {
            amount: 5,
            unitShort: "cloves",
            unitLong: "cloves",
          },
          metric: {
            amount: 5,
            unitShort: "cloves",
            unitLong: "cloves",
          },
        },
      },
      {
        id: 4517,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "vegetable-oil.jpg",
        consistency: "LIQUID",
        name: "grapeseed oil",
        nameClean: "grape seed oil",
        original: "1 + 1 T grapeseed oil",
        originalName: "1 T grapeseed oil",
        amount: 1,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 16424,
        aisle: "Ethnic Foods;Condiments",
        image: "soy-sauce.jpg",
        consistency: "LIQUID",
        name: "low sodium soy sauce",
        nameClean: "lower sodium soy sauce",
        original: "3T reduced-sodium soy sauce",
        originalName: "reduced-sodium soy sauce",
        amount: 3,
        unit: "T",
        meta: ["reduced-sodium"],
        measures: {
          us: {
            amount: 3,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 3,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 11304,
        aisle: "Produce",
        image: "peas.jpg",
        consistency: "SOLID",
        name: "peas",
        nameClean: "petite peas",
        original: "1 cup frozen peas",
        originalName: "frozen peas",
        amount: 1,
        unit: "cup",
        meta: ["frozen"],
        measures: {
          us: {
            amount: 1,
            unitShort: "cup",
            unitLong: "cup",
          },
          metric: {
            amount: 236.588,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 2047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "SOLID",
        name: "salt",
        nameClean: "table salt",
        original: "salt, to taste",
        originalName: "salt, to taste",
        amount: 8,
        unit: "servings",
        meta: ["to taste"],
        measures: {
          us: {
            amount: 8,
            unitShort: "servings",
            unitLong: "servings",
          },
          metric: {
            amount: 8,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
      {
        id: 11291,
        aisle: "Produce",
        image: "spring-onions.jpg",
        consistency: "SOLID",
        name: "scallion",
        nameClean: "spring onions",
        original: "additional chopped scallion tops for garnish",
        originalName: "additional chopped scallion tops for garnish",
        amount: 8,
        unit: "servings",
        meta: ["chopped", "for garnish"],
        measures: {
          us: {
            amount: 8,
            unitShort: "servings",
            unitLong: "servings",
          },
          metric: {
            amount: 8,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
      {
        id: 11291,
        aisle: "Produce",
        image: "spring-onions.jpg",
        consistency: "SOLID",
        name: "scallions",
        nameClean: "spring onions",
        original:
          "7 scallions, chopped (keep white/light green ends separate from dark green tops)",
        originalName:
          "scallions, chopped (keep white/light green ends separate from dark green tops)",
        amount: 7,
        unit: "",
        meta: [
          "dark",
          "green",
          "chopped",
          "(keep white/light ends separate from tops)",
        ],
        measures: {
          us: {
            amount: 7,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 7,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 4058,
        aisle: "Ethnic Foods",
        image: "sesame-oil.png",
        consistency: "LIQUID",
        name: "sesame oil",
        nameClean: "sesame oil",
        original: "2t toasted sesame oil",
        originalName: "toasted sesame oil",
        amount: 2,
        unit: "t",
        meta: ["toasted"],
        measures: {
          us: {
            amount: 2,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 2,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 12023,
        aisle: "Ethnic Foods;Spices and Seasonings",
        image: "sesame-seeds.png",
        consistency: "SOLID",
        name: "sesame seeds",
        nameClean: "sesame seeds",
        original: "toasted sesame seeds, optional",
        originalName: "toasted sesame seeds, optional",
        amount: 8,
        unit: "servings",
        meta: ["toasted"],
        measures: {
          us: {
            amount: 8,
            unitShort: "servings",
            unitLong: "servings",
          },
          metric: {
            amount: 8,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
    ],
    id: 716426,
    title: "Cauliflower, Brown Rice, and Vegetable Fried Rice",
    readyInMinutes: 30,
    servings: 8,
    sourceUrl:
      "http://fullbellysisters.blogspot.com/2012/01/cauliflower-fried-rice-more-veggies.html",
    openLicense: -1,
    image: "https://spoonacular.com/recipeImages/716426-556x370.jpg",
    imageType: "jpg",
    summary:
      'Cauliflower, Brown Rice, and Vegetable Fried Rice might be a good recipe to expand your side dish recipe box. Watching your figure? This gluten free, dairy free, lacto ovo vegetarian, and vegan recipe has <b>192 calories</b>, <b>7g of protein</b>, and <b>6g of fat</b> per serving. For <b>$1.12 per serving</b>, this recipe <b>covers 19%</b> of your daily requirements of vitamins and minerals. This recipe serves 8. This recipe from fullbellysisters.blogspot.com has 3689 fans. This recipe is typical of Chinese cuisine. From preparation to the plate, this recipe takes about <b>30 minutes</b>. Head to the store and pick up peas, broccoli, salt, and a few other things to make it today. Overall, this recipe earns an <b>awesome spoonacular score of 100%</b>. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/vegetable-fried-brown-rice-36199">Vegetable Fried Brown Rice</a>, <a href="https://spoonacular.com/recipes/vegetable-fried-cauliflower-rice-933261">Vegetable Fried Cauliflower Rice</a>, and <a href="https://spoonacular.com/recipes/easy-vegetable-fried-brown-rice-with-egg-802042">Easy Vegetable Fried Brown Rice with Egg</a>.',
    cuisines: ["Chinese", "Asian"],
    dishTypes: ["side dish"],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    occasions: [],
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: 'Remove the cauliflower\'s tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of "cauliflower rice."',
            ingredients: [
              {
                id: 10011135,
                name: "cauliflower florets",
                localizedName: "cauliflower florets",
                image: "cauliflower.jpg",
              },
              {
                id: 10111135,
                name: "cauliflower rice",
                localizedName: "cauliflower rice",
                image: "cauliflower.jpg",
              },
              {
                id: 11135,
                name: "cauliflower",
                localizedName: "cauliflower",
                image: "cauliflower.jpg",
              },
              {
                id: 20028,
                name: "couscous",
                localizedName: "couscous",
                image: "couscous-cooked.jpg",
              },
              {
                id: 20444,
                name: "rice",
                localizedName: "rice",
                image: "uncooked-white-rice.png",
              },
            ],
            equipment: [
              {
                id: 404771,
                name: "food processor",
                localizedName: "food processor",
                image: "food-processor.png",
              },
            ],
          },
          {
            number: 2,
            step: "Heat 1T butter and 1T oil in a large skillet over medium heat.",
            ingredients: [
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
              {
                id: 4582,
                name: "cooking oil",
                localizedName: "cooking oil",
                image: "vegetable-oil.jpg",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
          },
          {
            number: 3,
            step: "Add garlic and the white and light green pieces of scallion. Sauté about a minute.",
            ingredients: [
              {
                id: 11291,
                name: "green onions",
                localizedName: "green onions",
                image: "spring-onions.jpg",
              },
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
            ],
            equipment: [],
          },
          {
            number: 4,
            step: "Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.",
            ingredients: [
              {
                id: 11135,
                name: "cauliflower",
                localizedName: "cauliflower",
                image: "cauliflower.jpg",
              },
              {
                id: 0,
                name: "spread",
                localizedName: "spread",
                image: "",
              },
              {
                id: 4582,
                name: "cooking oil",
                localizedName: "cooking oil",
                image: "vegetable-oil.jpg",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
          },
          {
            number: 5,
            step: "Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom.",
            ingredients: [
              {
                id: 4047,
                name: "coconut oil",
                localizedName: "coconut oil",
                image: "oil-coconut.jpg",
              },
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
              {
                id: 0,
                name: "spread",
                localizedName: "spread",
                image: "",
              },
              {
                id: 20444,
                name: "rice",
                localizedName: "rice",
                image: "uncooked-white-rice.png",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
          },
          {
            number: 6,
            step: "Let it sit for about two minutes—so the rice can get toasted and a little crispy.",
            ingredients: [
              {
                id: 20444,
                name: "rice",
                localizedName: "rice",
                image: "uncooked-white-rice.png",
              },
            ],
            equipment: [],
            length: {
              number: 2,
              unit: "minutes",
            },
          },
          {
            number: 7,
            step: "Add the peas and broccoli and stir again.",
            ingredients: [
              {
                id: 11090,
                name: "broccoli",
                localizedName: "broccoli",
                image: "broccoli.jpg",
              },
              {
                id: 11304,
                name: "peas",
                localizedName: "peas",
                image: "peas.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 8,
            step: "Drizzle soy sauce and toasted sesame oil over rice.Cook for another minute or so and turn off heat.",
            ingredients: [
              {
                id: 4058,
                name: "sesame oil",
                localizedName: "sesame oil",
                image: "sesame-oil.png",
              },
              {
                id: 16124,
                name: "soy sauce",
                localizedName: "soy sauce",
                image: "soy-sauce.jpg",
              },
              {
                id: 20444,
                name: "rice",
                localizedName: "rice",
                image: "uncooked-white-rice.png",
              },
            ],
            equipment: [],
          },
          {
            number: 9,
            step: "Add chopped scallion tops and toss.I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.",
            ingredients: [
              {
                id: 12023,
                name: "sesame seeds",
                localizedName: "sesame seeds",
                image: "sesame-seeds.png",
              },
              {
                id: 16124,
                name: "soy sauce",
                localizedName: "soy sauce",
                image: "soy-sauce.jpg",
              },
              {
                id: 11291,
                name: "green onions",
                localizedName: "green onions",
                image: "spring-onions.jpg",
              },
              {
                id: 5006,
                name: "whole chicken",
                localizedName: "whole chicken",
                image: "whole-chicken.jpg",
              },
              {
                id: 18070,
                name: "toast",
                localizedName: "toast",
                image: "toast",
              },
              {
                id: 20444,
                name: "rice",
                localizedName: "rice",
                image: "uncooked-white-rice.png",
              },
              {
                id: 2047,
                name: "salt",
                localizedName: "salt",
                image: "salt.jpg",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/cauliflower-brown-rice-and-vegetable-fried-rice-716426",
  },
];

export default veganData;
